language: scala

jdk: oraclejdk8

scala:
   - 2.11.8

stages:
  - compile
  - test
  - run
  - doc

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

jobs:
  include:
    - stage: compile
      script: sbt ++$TRAVIS_SCALA_VERSION compile
    - stage: test
      script: sbt ++$TRAVIS_SCALA_VERSION test
    - stage: run
      script: sbt ++$TRAVIS_SCALA_VERSION run
    - stage: doc
      script: sbt ++$TRAVIS_SCALA_VERSION doc
