# --- General options --- #

# url is the full website URL
# baseurl is the website's URL without the hostname

# We are building a GitHub project page, thus we use these settings:
url: "https://andb0t.github.io/MLlab"
baseurl: "/MLlab"

# Name of website
title: MLlab

# Short description of your site
description: An experimental platform-independent machine learning library

# --- Navigation bar options --- #

# List of links in the navigation bar
navbar-links:
  Overview: "overview"
  Comparison: "comparison"
  Classification:
    - Logistic Regression: "classification/log_regression"
    - Perceptron: "classification/perceptron"
    - Naive Bayes: "classification/naive_bayes"
    - k-Nearest Neighbors: "classification/knearest_neighbor"
    - Decision Tree: "classification/decision_tree"
    - Boosted Decision Tree: "classification/boosted_decision_tree"
    - Random Forest: "classification/random_forest"
    - Support Vector Machine: "classification/support_vector_machine"
    - Multilayer Neural Network: "classification/ml_neural_network"
  Regression:
    - Linear: "regression/linear"
    - Bayes: "regression/bayes"
    - k-Nearest Neighbors: "regression/knearest_neighbor"
    - Decision Tree: "regression/decision_tree"
    - Multilayer Neural Network:  "regression/ml_neural_network"
  Clustering:
    - k-Means: "clustering/kmeans"
    - Self-organizing map: "clustering/selforg_map"
    - Hierarchical: "clustering/hierarchical"
  API: "api/index.html"
  Download: "download/download"

# --- Background colour/image options --- #

navbar-col: "#F5F5F5"
navbar-text-col: "#404040"
navbar-children-col: "#F5F5F5"
page-col: "#FFFFFF"
link-col: "#008AFF"
hover-col: "#0085A1"
footer-col: "#F5F5F5"
footer-text-col: "#777777"
footer-link-col: "#404040"

# --- Footer options --- #

# Change all these values or delete the ones you don't want.
# Important: you must keep the "name" parameter, everything else you can remove
author:
  name: Andreas Alexander Maier

# Select your active Social Network Links.
# Uncomment the links you want to show in the footer and add your information to each link.
# You can reorder the items to define the link order.
# If you want to add a new link that isn't here, you'll need to also edit the file _data/SocialNetworks.yml
social-network-links:
  rss: true
#  email: "someone@example.com"
#  facebook: daattali
  github: andb0t
#  twitter: daattali
#  reddit: yourname
#  google-plus: +DeanAttali
#  linkedin: daattali
#  xing: yourname
  stackoverflow: "7478814/andy-maier"
#  snapchat: deanat78
#  instagram: deanat78
#  youtube: user/deanat78
#  spotify: yourname
#  telephone: +14159998888
#  steam: deanat78
#  twitch: yourname
#  yelp: yourname

# Select which share links to show in posts
share-links-active:
  twitter: true
  facebook: true
  google: false
  linkedin: true

# How to display the link to the website in the footer
# Remove this if you don't want a link in the footer
# url-pretty: "MyWebsite.com"  # eg. "deanattali.com/beautiful-jekyll"

# --- Web Statistics Section --- #

# Fill in your Google Analytics ID to track your website using GA
#google_analytics: ""

# Google Tag Manager ID
#gtm: ""

# Matomo (aka Piwik) Web statistics
# Uncomment the following section to enable Matomo. The opt-out parameter controls
# whether or not you want to allow users to opt out of tracking.

#matomo:
#  site_id: "9"
#  uri: "demo.wiki.pro"
#  opt-out: true

# --- Misc --- #
# Fill in your Disqus shortname (NOT the userid) if you want to support Disqus comments
#disqus: ""

# Facebook App ID
# fb_app_id: ""

# Excerpt Word Length
# Truncates the excerpt to the specified number of words on the index page
excerpt_length: 50

# Character used to separate site title and description in HTML document title
# and RSS feed title
title-separator: "-"

# --- Don't need to touch anything below here (but you can if you want) --- #

# Output options (more information on Jekyll's site)
timezone: "Europe/Zurich"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5

kramdown:
  input: GFM

# Default YAML values (more information on Jekyll's site)
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true  # add comments to all blog posts
      social-share: true # add social media sharing buttons to all blog posts
  - scope:
      path: "" # all files
    values:
      layout: "page"
      show-avatar: true
  - scope:
      path: "img"
    values:
      image: true

# Use tags index page and make tags on each post clickable
link-tags: true

# Exclude these files from production site
exclude:
  - CNAME

# prose.io config
prose:
  rooturl: '_posts'
  media: 'img'
  ignore:
    - 404.html
    - feed.xml
    - _config.yml
    - /_layouts
    - /_includes
    - /css
    - /img
    - /js
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Post title"
          placeholder: "Title"
          alterable: true
      - name: "subtitle"
        field:
          element: "textarea"
          label: "Subtitle"
          placeholder: "A description of your post."
          alterable: true
      - name: "date"
        field:
          element: "text"
          label: "Date"
          help: "Enter date of post."
          placeholder: "yyyy-mm-dd"
          alterable: true
      - name: "image"
        field:
          element: "text"
          label: "Image"
          help: "Add a thumbnail image to your post."
          placeholder: "Thumbnail"
          alterable: true
      - name: "published"
        field:
          element: "checkbox"
          label: "Publish"
          help: "Check to publish post, uncheck to hide."

plugins:
  - jekyll-paginate
  - jekyll-sitemap

# Beautiful Jekyll / Dean Attali
# 2fc73a3a967e97599c9763d05e564189
